export const TOTAL_REPRESENTATIVE = 500
export const TOTAL_SENATOR = 250
export const PRIME_MINISTER_THRESHOLD =
  (TOTAL_REPRESENTATIVE + TOTAL_SENATOR) / 2 + 1
export const COUNCIL_THRESHOLD = TOTAL_REPRESENTATIVE / 2 + 1
